MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.ResNet50_conv4_body
  FASTER_RCNN: True
  NUM_CLASSES: 21
  LOAD_IMAGENET_PRETRAINED_WEIGHTS: True
  ANCHOR_POSES: 'configs/anchors/InTheWild-ResNet50_anchor_cfg.pkl'
NUM_GPUS: 8
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/resnet50_caffe.pth'
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 2700000
  STEPS: [0, 1800000, 2400000]
  MOMENTUM: 0.9
RPN:
  SIZES: (32, 64, 128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: ResNet.ResNet_roi_conv5_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  SCALES: (800,)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  USE_FLIPPED: False
  FG_THRESH: 0.5 
  BG_THRESH_HI: 0.5 
  BG_THRESH_LO: 0.0 
  BBOX_THRESH: 0.5
TEST:
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
  BBOX_REG: False

